spring:
  application:
    name: demo-customer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

server:
  port: 8083

demo-client:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 100
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1

