spring:
  application:
    name: demo-customer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

server:
  port: 8083

demo-client:
  ribbon:
    ConnectTimeout: 4000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000